/**
 * Easy-Post Desktop — remote MCP relay (Cloudflare Worker + Durable Object).
 *
 * Purpose: let an AI client (Claude Desktop, Cursor, …) reach a *sandboxed*
 * desktop app's MCP server without the app opening any inbound port. This is the
 * transport that makes AI-agent access work on the Mac App Store build, where the
 * App Sandbox forbids the local-subprocess design used elsewhere.
 *
 *   AI client  ──MCP over Streamable HTTP──▶  RELAY  ◀──outbound WebSocket──  desktop app
 *
 * The relay is a PURE TRANSPORT BRIDGE. It carries JSON-RPC frames between the
 * two sides and correlates responses by id. It never parses MCP semantics, never
 * sees the user's EasyPost API key, and never executes a tool — the desktop app
 * does all of that locally, exactly as it does today over stdio. Spending still
 * routes through the app's in-app human-approval queue.
 *
 * Pairing / auth: a high-entropy token, generated by the desktop app and shown to
 * the user, is presented by BOTH sides (the app on its WebSocket, the AI client
 * on its HTTP requests). The Durable Object instance is `idFromName(sha256(token))`,
 * so the two sides meet in the same object and nobody without the token can reach
 * it. The token is the pairing secret — treat it like a password; the app can
 * regenerate it to revoke access.
 *
 * Endpoints (token via `Authorization: Bearer <token>` header, or `/t/<token>/…`
 * path form for clients that cannot set headers):
 *   GET  /health           → liveness
 *   *    /connect          → desktop app WebSocket upgrade (the tool executor)
 *   POST /mcp              → AI client → app JSON-RPC (Streamable HTTP)
 *   GET  /mcp              → AI client SSE stream for server-initiated messages
 *
 * Security posture: a leaked token exposes READ/rate-shop access to that user's
 * shipping data (never spend — buying needs in-app approval), and only while the
 * app is online; it is revocable by regenerating the token in the app. The relay
 * refuses client requests whenever no app socket is connected.
 */

const TOKEN_MIN = 20;
// Long enough for a rate-shop round-trip to EasyPost, short enough that a dead
// app does not hang a client forever.
const REQUEST_TIMEOUT_MS = 30000;

async function sha256hex(input) {
  const digest = await crypto.subtle.digest("SHA-256", new TextEncoder().encode(input));
  return [...new Uint8Array(digest)].map((b) => b.toString(16).padStart(2, "0")).join("");
}

/** Bearer header first; then a `/t/<token>/…` path prefix for header-less clients. */
function extractToken(request, url) {
  const auth = request.headers.get("Authorization") || "";
  const m = auth.match(/^Bearer\s+(.+)$/i);
  if (m) return m[1].trim();
  const parts = url.pathname.split("/").filter(Boolean);
  if (parts[0] === "t" && parts.length >= 2) {
    try { return decodeURIComponent(parts[1]); } catch { return parts[1]; }
  }
  return null;
}

/** 'connect' | 'mcp' | null, ignoring an optional `/t/<token>` prefix. */
function endpointFromPath(url) {
  let parts = url.pathname.split("/").filter(Boolean);
  if (parts[0] === "t") parts = parts.slice(2);
  const last = parts[parts.length - 1];
  return last === "connect" || last === "mcp" ? last : null;
}

function rpcError(id, code, message) {
  return { jsonrpc: "2.0", id: id === undefined ? null : id, error: { code, message } };
}

export default {
  async fetch(request, env) {
    const url = new URL(request.url);

    if (url.pathname === "/health") {
      return Response.json({ ok: true, service: "easypost-mcp-relay" });
    }
    if (url.pathname === "/") {
      return new Response(
        "Easy-Post Desktop remote MCP relay. GET /health for status.\n",
        { headers: { "content-type": "text/plain" } }
      );
    }

    const endpoint = endpointFromPath(url);
    if (!endpoint) return new Response("not found", { status: 404 });

    const token = extractToken(request, url);
    if (!token || token.length < TOKEN_MIN) {
      return new Response("unauthorized: missing or too-short pairing token", { status: 401 });
    }

    // Both sides of a pairing route to the same object via the token hash.
    const stub = env.RELAY.get(env.RELAY.idFromName(await sha256hex(token)));
    return stub.fetch(request);
  },
};

export class RelayHub {
  constructor(state, env) {
    this.state = state;
    this.env = env;
    this.app = null;            // the desktop app's WebSocket (the tool executor)
    this.pending = new Map();   // relayId -> { resolve, clientId, timer }
    this.seq = 0;
    this.sse = new Set();       // open SSE writers for server-initiated messages
  }

  async fetch(request) {
    const endpoint = endpointFromPath(new URL(request.url));
    if (endpoint === "connect") return this.handleAppConnect(request);
    if (endpoint === "mcp") {
      if (request.method === "POST") return this.handleClientPost(request);
      if (request.method === "GET") return this.openSse();
      if (request.method === "DELETE") return new Response(null, { status: 204 });
      return new Response("method not allowed", { status: 405 });
    }
    return new Response("not found", { status: 404 });
  }

  // --- desktop app side (WebSocket) ---------------------------------------

  handleAppConnect(request) {
    if ((request.headers.get("Upgrade") || "").toLowerCase() !== "websocket") {
      return new Response("expected a websocket upgrade", { status: 426 });
    }
    const pair = new WebSocketPair();
    const client = pair[0];
    const server = pair[1];
    server.accept();

    // Only one app per pairing; a reconnect replaces the stale socket.
    if (this.app) { try { this.app.close(1012, "replaced by a new connection"); } catch {} }
    this.app = server;

    server.addEventListener("message", (ev) => this.onAppMessage(ev.data));
    const drop = () => {
      if (this.app === server) {
        this.app = null;
        this.failPending("The desktop app disconnected.");
      }
    };
    server.addEventListener("close", drop);
    server.addEventListener("error", drop);

    try { server.send(JSON.stringify({ type: "relay.hello", ts: Date.now() })); } catch {}
    return new Response(null, { status: 101, webSocket: client });
  }

  onAppMessage(data) {
    let msg;
    try {
      msg = JSON.parse(typeof data === "string" ? data : new TextDecoder().decode(data));
    } catch {
      return;
    }
    if (msg && msg.type === "ping") {
      try { this.app.send(JSON.stringify({ type: "pong", ts: Date.now() })); } catch {}
      return;
    }
    // A reply to a request we relayed: restore the client's original id and resolve.
    if (msg && msg.id !== undefined && this.pending.has(msg.id)) {
      const p = this.pending.get(msg.id);
      this.pending.delete(msg.id);
      clearTimeout(p.timer);
      p.resolve({ ...msg, id: p.clientId });
      return;
    }
    // Anything else the app initiates (notifications) → fan out to SSE listeners.
    this.broadcast(msg);
  }

  failPending(reason) {
    for (const p of this.pending.values()) {
      clearTimeout(p.timer);
      p.resolve(rpcError(p.clientId, -32001, reason));
    }
    this.pending.clear();
  }

  // --- AI client side (Streamable HTTP) -----------------------------------

  async handleClientPost(request) {
    let body;
    try { body = await request.json(); } catch { return new Response("bad json", { status: 400 }); }
    const batch = Array.isArray(body) ? body : [body];

    if (!this.app) {
      const offline = (id) => rpcError(id, -32001,
        "The Easy-Post Desktop app is offline. Open it and enable AI agent access.");
      const errs = batch.filter((m) => m && m.id !== undefined).map((m) => offline(m.id));
      const payload = Array.isArray(body) ? errs : (errs[0] ?? offline(null));
      return this.json(payload);
    }

    const responses = [];
    let sessionId = null;
    for (const m of batch) {
      if (!m || m.id === undefined) {           // notification: forward, no reply
        try { this.app.send(JSON.stringify(m)); } catch {}
        continue;
      }
      if (m.method === "initialize") sessionId = crypto.randomUUID();
      responses.push(await this.relayOne(m));
    }

    if (responses.length === 0) return new Response(null, { status: 202 });
    const payload = Array.isArray(body) ? responses : responses[0];
    return this.json(payload, sessionId);
  }

  relayOne(message) {
    const relayId = "relay-" + (++this.seq);
    const clientId = message.id;
    return new Promise((resolve) => {
      const timer = setTimeout(() => {
        this.pending.delete(relayId);
        resolve(rpcError(clientId, -32002, "Timed out waiting for the desktop app."));
      }, REQUEST_TIMEOUT_MS);
      this.pending.set(relayId, { resolve, clientId, timer });
      try {
        this.app.send(JSON.stringify({ ...message, id: relayId }));
      } catch {
        clearTimeout(timer);
        this.pending.delete(relayId);
        resolve(rpcError(clientId, -32001, "Could not reach the desktop app."));
      }
    });
  }

  openSse() {
    const { readable, writable } = new TransformStream();
    const writer = writable.getWriter();
    const enc = new TextEncoder();
    const entry = { writer, enc };
    this.sse.add(entry);
    writer.write(enc.encode(": connected\n\n")).catch(() => this.sse.delete(entry));
    return new Response(readable, {
      headers: {
        "content-type": "text/event-stream",
        "cache-control": "no-cache",
        "connection": "keep-alive",
      },
    });
  }

  broadcast(msg) {
    if (this.sse.size === 0) return;
    const line = `data: ${JSON.stringify(msg)}\n\n`;
    for (const e of this.sse) {
      e.writer.write(e.enc.encode(line)).catch(() => this.sse.delete(e));
    }
  }

  json(payload, sessionId) {
    const headers = { "content-type": "application/json" };
    if (sessionId) headers["Mcp-Session-Id"] = sessionId;
    return new Response(JSON.stringify(payload), { headers });
  }
}
